Check
Tihorez/Ftracker pull request #2
Opened 2024-07-18 22:19 UTC by Tihorez

2024-07-19 16:37 UTC, dirtymew requested changes
Привет Тихон

хорошая работа - но падают тесты - стоит проверить формулы

2024-07-19 16:37 UTC, dirtymew commented on .idea/.gitignore
> +# Default ignored files
это все лучше добавить в .gitignore и не коммитеть в ветку

2024-07-19 16:37 UTC, dirtymew commented on ftracker.go
> +		dist = float64(lengthPool*countPool) / mInKm               // вызовите здесь необходимую функцию
не уверен что так правильно считать дистанцию - а не через кол-во гребков

2024-07-20 21:16 UTC, Tihorez commented
> Привет Тихон
> 
> хорошая работа - но падают тесты - стоит проверить формулы

Привет
Поправил, теперь все тесты зеленые и в блоке плавания тоже
По всей видимости, ошибка в формуле нахождения дистанции при плавании в самом задании.

2024-07-20 21:17 UTC, Tihorez commented on ftracker.go
> +		dist = float64(lengthPool*countPool) / mInKm               // вызовите здесь необходимую функцию
Поправил до зеленого теста

2024-07-20 21:18 UTC, Tihorez commented on .idea/.gitignore
> +# Default ignored files
Убрал в .gitignore

2024-07-20 23:27 UTC, dirtymew commented
> > Привет Тихон
> > хорошая работа - но падают тесты - стоит проверить формулы
> 
> Привет Поправил, теперь все тесты зеленые и в блоке плавания тоже По всей видимости, ошибка в формуле нахождения дистанции при плавании в самом задании.

@Tihorez если не сложно покажи где именно ошибка в задании... или ты про формулу средней скорости - там да через бассейны

тут дело не в физической точности а в точности реализации запрошеной логики )

2024-07-20 23:30 UTC, dirtymew approved these changes
Тихон 

теперь все ок

зачет

2024-07-21 02:26 UTC, Tihorez commented
Ага, вроде должно быть через параметры бассейна

2024-07-21 02:27 UTC, Tihorez commented
> > > Привет Тихон
> 
> > > хорошая работа - но падают тесты - стоит проверить формулы
> 
> > 
> 
> > Привет Поправил, теперь все тесты зеленые и в блоке плавания тоже По всей видимости, ошибка в формуле нахождения дистанции при плавании в самом задании.
> 
> 
> 
> @Tihorez если не сложно покажи где именно ошибка в задании... или ты про формулу средней скорости - там да через бассейны
> 
> 
> 
> тут дело не в физической точности а в точности реализации запрошеной логики )

Ага, вроде должно быть через параметры бассейна)

2024-07-21 02:41 UTC, merged